Add pre-installs for deployment factories
ethereum/RIPs pull request #30
Opened 2024-07-10 06:58 UTC by rmeissner

This RIP proposes a set of known deployment factories that should be pre-installed on every rollup to make it easier to deploy contracts in a trustless, deterministic way. In the best case this also allows for same address deployments of the same contracts across multiple chains.

2024-07-10 12:17 UTC, CarlBeek commented
Hey @rmeissner I have assigned the next available number, please update to RIP-7740

2024-07-11 08:52 UTC, abcoathup commented on RIPS/rip-7740.md
> +discussions-to: https://ethereum-magicians.org/t/eip-proposal-create2-contract-factory-precompile-for-deployment-at-consistent-addresses-across-networks/6083/29
Suggest creating a new topic on Eth Magicians to discuss this RIP

2024-08-22 18:18 UTC, oneski commented
any consideration to adding multicall to this list?

2025-01-13 15:25 UTC, nconsigny requested changes
Should change to RRC before merging

2025-01-13 15:25 UTC, nconsigny commented on RIPS/rip-7740.md
> +category: Core
```suggestion
category: RRC
```

2025-01-15 19:12 UTC, rmeissner commented
@oneski @Agusx1211 I added a [new discussion thread](https://ethereum-magicians.org/t/rrc-7740-add-pre-installs-for-deployment-factories/22544) to align on the open questions

2025-01-15 20:39 UTC, nconsigny approved these changes
LGTM

2025-01-15 20:40 UTC, merged