RIP-7755 Updates
ethereum/RIPs pull request #43
Opened 2024-12-10 17:41 UTC by jackchuma

- Improves proposal structure (i.e. improves structure of existing sections and adds missing common sections such as `Rationale`, `Security Considerations` and `Copyright`).
- Updates specification to describe interface definitions and intended behavior as opposed to strict implementation details
- Moves implementation examples into `assets` directory and references from `Reference Implementation` section
- Updates referenced implementations with latest proof-of-concept work
- Adds new diagram to improve storage proof explanation clarity

2025-01-07 17:14 UTC, wilsoncusack approved these changes

2025-01-13 13:48 UTC, nconsigny requested changes
LGTM ;

As discussed @wilsoncusack @jackchuma we'd need you guys to recategorize to RRC as this corresponds better to the RIP. could you update 
https://github.com/ethereum/RIPs/blob/c8e5881044b792da59b5848bd68a79b82d7b1848/RIPS/rip-7755.md?plain=1#L9

category: Core  => category: RRC

2025-02-27 00:07 UTC, nconsigny commented
up @wilsoncusack @jackchuma

2025-03-12 22:58 UTC, nconsigny approved these changes
LGTM

2025-03-12 22:58 UTC, merged